matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.2.2"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.2.2"
